version: '3'

services:
  mariadb:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - "3307:3306"

  fastapi:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - mariadb
