version: '3.8'

services:
  mariadb:
    image: mariadb
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root

  fastapi:
    build: .
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - mariadb
